import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Login</Link>
        </li>
        <li>
          <Link to="/loginone">LoginOne</Link>
        </li>
        <li>
          <Link to="/attendancesheet">Attendancesheet</Link>
        </li>
        <li>
          <Link to="/attendancesheetgeneratesheet">
            AttendancesheetGenerateSheet
          </Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/reportsone">ReportsOne</Link>
        </li>
        <li>
          <Link to="/attendancesheettaken">Attendancesheettaken</Link>
        </li>
        <li>
          <Link to="/student">Student</Link>
        </li>
        <li>
          <Link to="/dashboardone">DashboardOne</Link>
        </li>
        <li>
          <Link to="/absenceapplication">Absenceapplication</Link>
        </li>
        <li>
          <Link to="/attendancesheetafterattendancetaken">
            AttendancesheetAfterattendancetaken
          </Link>
        </li>
        <li>
          <Link to="/reports">Reports</Link>
        </li>
        <li>
          <Link to="/teacher">Teacher</Link>
        </li>
        <li>
          <Link to="/teacheraddteacher">TeacherAddteacher</Link>
        </li>
        <li>
          <Link to="/subject">Subject</Link>
        </li>
        <li>
          <Link to="/subjectaddsubjectone">SubjectAddsubjectOne</Link>
        </li>
        <li>
          <Link to="/studentone">StudentOne</Link>
        </li>
        <li>
          <Link to="/subjectaddsubject">SubjectAddsubject</Link>
        </li>
        <li>
          <Link to="/logintwo">LoginTwo</Link>
        </li>
        <li>
          <Link to="/sendabsentletter">SendAbsentLetter</Link>
        </li>
        <li>
          <Link to="/absenceapplicationone">AbsenceapplicationOne</Link>
        </li>
        <li>
          <Link to="/alert">Alert</Link>
        </li>
        <li>
          <Link to="/table">Table</Link>
        </li>
        <li>
          <Link to="/buttonstyle">Buttonstyle</Link>
        </li>
        <li>
          <Link to="/dashboardtwo">DashboardTwo</Link>
        </li>
        <li>
          <Link to="/form">Form</Link>
        </li>
        <li>
          <Link to="/fourhundredfour">FourHundredFour</Link>
        </li>
        <li>
          <Link to="/tabletwo">TableTwo</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
